### ISSUE TITLE
Реализовать Action, Use, DontUse

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#10]
**Класс Action:**
Абстрактный класс. Должен иметь функции:
1. Void act(Player* player) - действие текущего Действия. Переопределят дочерние классы.

**Класс Use:**
Дочерний от класса Action. Переопределяет следующие функции:
1. Конструктор Use(Chest*, int index) - конструктор, привязывающий Use к конкретному Chest с конкретным index
2. Void act(Player* player) - вызывает Chest::use(Player*, int index) от Chestа к которому был привязан с помощью конструктора _(см Chest(#5))_
3. Chest* getChest() - возвращает Chest, к которому привязан Use.

**Класс DontUse:**
Дочерний от класса Action. Переопределяет следующие функции:
1. Конструктор DontUse(Trap*, int index) - конструктор, привязывающий Use к конкретному Chest с конкретным index
2. Void act(Player* player) - вызывает Trap::dontUse(Player*, int index) от Trapа к которому был привязан с помощью конструктора _(см Trap(#13))_
3. Trap* getChest() - возвращает Trap, к которому привязан DontUse.

**Comment by NAGIBATOR05** [comment]
Моë

**Comment by TEHEK1** [comment]
Немного изменил. Посмотри
