### ISSUE TITLE
Реализовать Trap и одного конкретного наследника

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#13]
**Класс Trap:**
Сделать по подобию #5. Дочерний от класса Chest.  Переопределяет: 
1. void turn(Player*, index) - вызывает Player.getMonitor().draw()(см Player(#14)  и вызывает  addAction(Player*, &Use(this)) и вызывает  addAction(Player*, &DontUse(this))
2. Void use(Player*, int index) - накладывает на игрока соответствующие эффекты, дает соответствующие предметы. Эффекты и предметы генерируются рандомно и иначе чем в Chest и вызывает Player.getMap().getCell(Player.getPosition()).freeMoves(Player*, index). Меняет картинку, возвращаемую draw и не позволяет вызвать снова(В идеале вызывает removeAction(Player*, *компаратор, которому соответствует this*)(см Event(#14) и Chest(#5)) и при следующем вызове turn() не вызывает  addAction(Player*, &Use(this)*). 
4. Void dontUse(Player*, int index) - накладывает на игрока соответствующие эффекты и вызывает Player.getMap().getCell(Player.getPosition()).freeMoves(Player*, index)
5. Переопределить draw()(см Event)

**Comment by supersl555** [comment]
Не совсем понимаю, что делать, но разберусь)

**Comment by Abdkait** [comment]
хочу
