### ISSUE TITLE
Реализовать Player

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#14]
Игрок. Должен иметь поля Inventory inventory, Position position, std::set<Action*> actions. Должен быть friend с  ActionChanger, PositionChanger, InventoryChanger. Должен иметь функции:
1. Squad getHeroes() - возвращает список героев. _(#39)_
2. Monitor* getMonitor() - Возвращает связанный с Player UI. 
3. Position getPosition() - Возвращает текущую позицию.
4. std::set<std::unique_ptr<Action>> getActions() - Возвращает actions
5. Inventory getInventory() - возвращает инвентарь
6. Map* getMap() - Возвращает карту.

**Comment by ilyinAD** [comment]
йоу
