### ISSUE TITLE
Реализовать MoveLeft, MoveRight, ChooseNextRoom

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#15]
**Класс MoveLeft:**
Дочерний от Action, ActionsChanger, PositionChanger. Переопределяет следующие функции:
1. void act(Player* player) - setPosition(&player, Map::MoveLeft(Position))_(см Класс Map #1 и Класс Player #14)_, накладывает дебаф за движение влево и вызывает Cell::generateEvents если не вызывал до этого на этой клетке(По идее такого не должно произойти). После чего вызывает Cell.getEvents[i].turn(player)(см Cell и Event). Вызывает returnToDefault(player).

**Класс MoveRight:**
Дочерний от Action, ActionsChanger, PositionChanger. Переопределяет следующие функции:
1. void act(Player* player) - Вызывает setPosition(&player, Map::MoveRight(Position))_(см Класс Map #1 и Класс Player #14)_ и вызывает Cell::generateEvents если не вызывал до этого на этой клетке. После чего вызывает Cell.getEvents[i].turn(player)(см Cell и Event). Вызывает returnToDefault(player)

**Класс ChooseNextRoom:**
Дочерний от Action, PositionChanger. Переопределяет следующие функции:
1. ChooseNextRoom(необходимые аргументы) - конструктор _(спросить у Андрея или см #1)_
2. void act(Player* player) - Меняет у Position_(см Класс PositionChanger #18)_ Playerа начальную и конечную комнату движения в коридоре в соответсвии с аргументами конструктора. _(см Класс Map #1 функция Map::setRooms)_

**Comment by hlsht** [comment]
закрепи за мной эту таску

**Comment by Abdkait** [comment]
иди ко мне
