### ISSUE TITLE
Реализовать ActionsChanger

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#17]
**Класс ActionsChanger**
Должен иметь функции. _Рекомендуется посмотреть класс Player(#14)_
protected:
1. void addAction(Player*, std::shared_ptr\<Action\>) - добавляет Action в Player.actions
2. void removeAction(Player*, std::function<bool (std::set\<std::shared_ptr\<Action\>\>::iterator)>) - удаляет все подходящие под компаратор дейтсивия из Player.action.
3. void returnToDefault(Player*) - возвращает Player.actions в дефолтное состояние(пока просто делает actions пустым)
4. std::set<std::unique_ptr<Action>>& getActions(Player*) - возвращает ссылку на Player.actions

**Comment by ilyinAD** [comment]
я бэру

**Comment by NAGIBATOR05** [comment]
я бэру
