### ISSUE TITLE
Реализовать PositionChanger и InventoryChanger

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#18]
**Класс PositionChanger**
Должен иметь функции:
1. void setPosition(Player*, Position) - меняет Player.position на  аргумент Position.

**Класс InventoryChanger**
Должен иметь функцию
1. Inventory& getInventory(Player*) - возвращает ссылку на Player.inventory

**Comment by superesl555** [comment]
Беру
