### ISSUE TITLE
Реализовать Monitor. Хотя бы взаимодействие с клавиатуры.

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#2]
**Класс Monitor:**
Должен иметь функции:
1. draw(Player* player) - Отрисовка интерфейса соответствующего Player. Примерная реализация:
    1. Запрашиваем player.getMap().getCell(player.getPosition()).draw()(см Player, Map и Cell).
    2. Запрашиваем player.getHeroes()[i].draw()(см Player и Hero).
    3. Запрашиваем player.getMap().draw()(см Player и Map)
    4. По полученным данным отрисовать текущее состояние игры.
2. draw() - отрисовка интерфейса привязанного к Monitor Playerа. Вызывает draw(Player* player).
3. Void keyEvent(char) - обработка клавиши.
4. Void keyEvent() - обработка нажатой клавиши. После нажатия клавиши вызывает keyEvent(char) от нажатой клавиши.

**Comment by 4evrinspace** [comment]
Sign this very big task to me (Denis)
