### ISSUE TITLE
Реализовать Cell, Room, Hall

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#3]
**Класс Cell:**
Должен хранить информацию о ячейке(коридор или комната). Должен иметь функции 
1. freeMoves(Player*, int index) - счетчик ивентов, позволяющих уйти из клетки. При вызове добавляет index в множество. Если после очередного вызова количество вызовов этой функции с РАЗНЫМИ значениями index равно getEvents.size(), добавляет в контейнер _actions_ Playerа указатели на MoveLeft, MoveRight
1. generateEvents() - переопределят дочерние классы.
2. std::vector<Event*> getEvents() - возвращает контейнер указателей на Эвенты этой Cell.
3. getLevel() - Уровень сложности клетки. (Пока можно хоть случайное число выдавать. Позже подредактируем)

**Класс Room:**
Дочерний от Cell(наследуется от Cell). Переопределяет generateEvents в соответствии с правилами.(добавляет в events два случайных Эвента и ChooseRoomEvent(по итогу в events должно быть 3 ивенты)).

**Класс Hall:**
Дочерний от Cell(наследуется от Cell). Предопределяет generateEvents в соответствии с правилами.(добавляет в events один случайный Эвент(по итогу в events должен быть один ивент)).

**Comment by Abdkait** [comment]
хочу сделать

**Comment by TEHEK1** [comment]
Ок. Бери

**Comment by TEHEK1** [comment]
Я привяжу
