### ISSUE TITLE
Реализовать Entity

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#37]
**enum class Characteristic**
accuracyModifier = trick::hash("accuracyModifier"), dodge = trick::hash,("dodge"), defence = trick::hash("defence"), speed = trick::hash("speed"), HP = trick::hash("HP"),  maxHP = trick::hash("maxHP"), marked = trick::hash("marked"), turnable = trick::hash("turnable"), movable = trick::hash("movable"), enemyType = trick::hash("enemyType"), minDamage = trick::hash("minDamage"), maxDamage = trick::hash("maxDamage"), criticalDamageChance = trick::hash("criticalDamageChance"), 

**enum class Resistances**
Stun = trick::hash("Stun"), Blight = trick::hash("Blight"), Bleed= trick::hash("Bleed"), Debuff = trick::hash("Debuff"), Move = trick::hash("Move")
**Класс Entity**(Починить заголовок)
    friend с EntityChanger
имеет protected поля
    std::set\<std::shared_ptr\<Skill>> m_skills _(#7)_
    std::map\<std::string, int\> m_characteristics
    std::set\<std::shared_ptr\<Effect>> m_effects _(#8)_
имеет методы
1. get(size_t) - возвращает характеристику + сумма Characteristic по modificator всех m_effects
2. get(dodge) - если get(turnable)\<0, возвращает 0, иначе как get(Сharacteristic).
3. getEffects() - возвращает m_effects
4. getSkills() - возвращает m_skills
5. string getName() - возвращает имя персонажа.
6. std::set\<std::shared_ptr\<Skill>> getSkills() - возвращает список умений героя
7. final метод bool isAlive(), который возвращает true, если Hp\>0 и false иначе
8. final метод bool isTurnable(), который возвращает true, если turnable\>=0 и false иначе
9. final bool dodged() - генерирует случайное число от 0 до 100. Если число меньше get(dodge), возвращает true. иначе возвращает false
10. final bool resisted(size_t effectHash) - генерирует случайное число от 0 до 100. Если число меньше get(effectHash), возвращает true. иначе возвращает false

**Класс EntityChanger**
Имеет доступ к полям Entity. должен иметь protected методы:
1. set(size_t, int) для всех полей класса Entity _(#8)_.
Ограничения: Если вызван set(HP, newHP) и newHP\>m_maxHP, то m_HP=m_maxHP
Ни одно значение не может упасть ниже нуля, коме m_HP(то есть если вызван set(*, value) и value\<0, то переменная равна 0)
2. turnEffects() - для каждого эффекта из m_effects вызывает turn. _(#8)_
6. endBattleTurnEffects() - для каждого эффекта из m_effects вызывает endBattleTurn. _(#8)_
7. addEffect(std::shared\<Effect\>) - добавляет в m_effects. если dynamic_cast Effect в ImmediateEffect не null_ptr вызывает turn. 
8. removeEffect(std::shared\<Effect\>) - удаляет из m_effects.
11. addSkill(std::shared\<Effect\>) - добавляет в m_skills.
12. removeSkill(std::shared\<Effect\>) - удаляет из m_skills.

**Класс Hero**
Дочерний от Entity
Имеет также характеристики DamageMin, DamageMax

**Comment by superesl555** [comment]
Забираю
