### ISSUE TITLE
Реализовать Squad и SquadChanger, BattleField и BattleFieldChanger

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#39]
**Класс Squad**
friend с SquadChanger
хранит какой-то контейнер указателей на Entity, размера size.
Должен иметь конструкторы 
1. Squad(std::vector\<std::shared_ptr\<Entity\>\>)
2. Squad(std::vector\<std::shared_ptr\<Entity\>\>, size) - дополняет null_ptrами до size
Должен иметь методы:
1. std::vector\<std::shared_ptr\<Entity\>\> getEntities() - возвращает вектор указателей на Entity в порядке их расположения.
2. std::vector\<std::shared_ptr\<Entity\>\> getEntity(int index) - возвращает Entity, расположенный по индексу index
**Класс SquadChanger**
Должен иметь методы:
1. static void move(std::shared_ptr\<Squad\>, int index1, int index2) - Если index1\<0 или index1\>=size, бросает ошибку. Если index2\<0, выполнить функцию при index2=0, если index2\>=size, выполнить функцию при index2=size-1. При index1=index2, ничего не делать. Если в index2 нет объекта, просто перемещает объект из index1 в index2. Иначе объект, находящийся в index2 смещается на один в ту сторону, с какой стороны от него находится index1(перемещается в index2-1, если index1\<index2, перемещается в index2+1б если index1\>index2), если в этой ячейке тоже находится объект, то происходит тоже самое, но уже для этого объекта(он смещается на 1, если index2 смещался на 1 и смещается на -1, если index2 смещался на -1) и так до тех пор, пока следующего объекта не будет(незанятая ячейка) или следующий объект не является index1. Тогда надо выполнить циклический сдвиг на отрезке [index1,index2]. Лучше мне напиши. На пальцах проще объясняется.
2. static void move(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity, int index2) - ищет entity в контейнере и если не находит, кидает ошибку. иначе вызывает move(std::shared_ptr\<Squad\>, найденный индексб index2)
3. static void relativeMove(std::shared_ptr\<Squad\>, int index, int offset) - вызывает move(std::shared_ptr\<Squad\>, index, offset)
4. static void relativeMove(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity, int offset) - вызывает move(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity, offset)
5. static void remove(std::shared_ptr\<Squad\>, index) - удаляет объект по индексу, не смещая остальные объекты и не меняя size(то есть тупо nullptr присваивает)
6. static void remove(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity) - Если не находит entity, кидает ошибку. Иначе удаляет объект, не смещая остальные объекты и не меняя size(то есть тупо nullptr присваивает)
7. static void add(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity, int index) - если index свободен, ставит туда entity, не смещая остальные объекты и не меняя size. Иначе бросает ошибку.
8. static void add(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity) - если есть свободное место, ставит туда entity, не смещая остальные объекты и не меняя size. Иначе кидает ошибку. Старается поставить в наименьший index.

**Класс BattleField**
По сути поле боя. должен хранить указатели на два Squad а. _(#39)_
friend с BattleFieldChanger
Должен иметь конструктор 
1. BattleField(std::shared_ptr\<Squad\>, std::shared_ptr\<Squad\>)
Должен иметь функции:
1. std::vector\<std::shared_ptr\<Entity\>\> getEntities() - возвращает Entity поля боя. Причем поле, которое шло в конструкторе первым, должно выводиться в обратном порядке
2. std::shared_ptr\<Squad\> getSquad(std::shared_ptr\<Entity\>)- бросает ошибку, если ни в одном Squad нет или есть в обоих std::shared_ptr<Entity>. Иначе возвращает Squad, в котором находится std::shared_ptr\<Entity\>. 
3. bool areAllies(std::shared_ptr<Entity>, std::shared_ptr\<Entity\>)- бросает ошибку, если хоть одного std::shared_ptr\<Entity\> нет ни в одном Squad. Иначе возвращает true, если указатели в одном Squad и false иначе.
**Класс BattleFieldChanger**
Дочерний от SquadChanger
должен иметь static protected методы:
1. static void move(std::shared_ptr\<BattleField\>, std::shared_ptr\<Entity\>entity, int index2)- Если в BattlefField нет entity, бросает ошибку. Иначе вызывает соответствующий метод от Squad, к которому принадлежит entity. 
2. static void relativeMove(std::shared_ptr\<BattleField\>, std::shared_ptr\<Entity\>entity, int offset) - Если в BattlefField нет entity, бросает ошибку. Иначе вызывает соответствующий метод от Squad, к которому принадлежит entity. 
3. static void remove(std::shared_ptr\<BattleField>, std::shared_ptr\<Entity\>entity) - Если не находит entity, кидает ошибку. Иначе вызывает соответствующий метод от Squad, к которому принадлежит entity. 
4.  static void add(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity, int index)
5. using static void SquadChanger::add(std::shared_ptr\<Squad\>, std::shared_ptr\<Entity\>entity).

**Comment by J3olchara** [comment]
мне закинь, я сначала его сделаю потом ту миддловускую таску
