### ISSUE TITLE
Реализовать  Event, ChooseRoomEvent, EmptyCell(with sprite)

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#4]
**Класс Event:**
Должен хранить информацию об Эвенте. Дочерний от ActionChanger. Должен иметь функции:

public:
1. Void turn(Player*, int index) - Переопределят дочерние классы.
4. *Что-то* draw() - Возвращает спрайт ивента в любом удобном виде.

**Класс ChooseRoomEvent:** 
Ивент, позволяющий в комнате выбирать следующую комнату. Дочерний от класса Event. Переопределяет:
1. void turn(Player*, int index) - вызывает Player.getMonitor().draw() _(см Player(#14))_  и вызывает Player.getMap().getCell(Player.getPosition()).freeMoves(Player*, index). вызывает addActions(Player*, ChooseRoom*) _(#15)_ для всех доступных ChooseRoom _(см класс Map(#1))_
2. *Что-то* draw() - возвращает пустоту

**Класс EmptyCell:** 
Пустой коридор. Дочерний от класса Event. Переопределяет:
1. void turn(Player*, int index) - вызывает Player.getMonitor().draw()) _(см Player(#14)_)  и вызывает Player.getMap().getCell(Player.getPosition()).freeMoves(Player*, index)
2. *Что-то* draw()

**Comment by J3olchara** [comment]
my (Arseniy)

**Comment by TEHEK1** [comment]
Не. Я нашел мидловскую таску, которая нужна побыстрее

**Comment by TEHEK1** [comment]
Закрепил
