### ISSUE TITLE
Реализовать Main

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#45]
**Класс Main**
Синглетон
1. функция setSeed(size_t) - ставит seed. До того как был вызван seed = random_device
2. функция size_t getSeed() - возвращает seed
3. функция Monitor* getGame() - создает Monitor, Player, генерирует карту. _см(#1)_, _см(#2)_, _см(#34)_,  Связывает их друг с другом.(учесть утечки памяти)  Возвращает указатель на монитор.
4. getEvent() - выдает случайный по сиду  Event из зарегистрированных(гугли фабрика классов). К тому моменту, надеюсь по папкам раскидают Eventы. _(#4)_
5. getEntity() - выдает случайный по сиду Entity из зарегистрированных (гугли фабрика классов). надеюсь по папкам раскидают Entity. _(#37 )_
6. getRandomNumber(int minValue, int maxValue) - возвращает случайное число по сиду seed

**Comment by ilyinAD** [comment]
бэру
