### ISSUE TITLE
Realize Chest and one derived class(Some sample of Chest)

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#5]
**Класс Chest:**
Коридор с предметом(Комната может иметь два таких). Дочерний от класса Event, InventoryChanger. Переопределяет: 
1. void turn(Player*, int index) - вызывает Monitor::draw()(см UI), вызывает addAction(Player*, &Use(this))  и вызывает Player.getMap().getCell(Player.getPosition()).freeMoves(Player*, index) у клетки, на которой находится игрок.(см класс Cell, класс Player).
Должен иметь функции:
2. Void use(Player*, int index) - накладывает на игрока соответствующие эффекты, дает соответствующие предметы. Эффекты и предметы генерируются рандомно. (Пока может быть виртуально для переопределения в Trap. Этот момент лучше обсудить)(Уточняется у Дениса), меняет картинку, возвращаемую draw и не дает вызывать заново.(В идеале вызывает removeAction(Player*, &Use(this)) и при следующем вызове turn() не вызывает addActions(Player*, &Use(this)).)
3. Переопределить draw()(см Event) #4

**Comment by ilyinAD** [comment]
я беру

**Comment by TEHEK1** [comment]
Закрепил

**Comment by TEHEK1** [comment]
Немного поменял. Чекни изменения
