### ISSUE TITLE
Реализовать врагов

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#50]
**Класс Enemy**
Дочерний от Entity

Все враги должны быть в namespace enemies::ИмяПерсонажа и дочерние от Enemy
Скилы предоставят. Они будут лежать в enemies::ИмяПерсонажа::НазваниеСкила

**BrigandFusilier**
https://darkestdungeon.wiki.gg/wiki/Brigand_Fusilier

**BrigandRaider**
https://darkestdungeon.wiki.gg/wiki/Brigand_Raider

**CultistAcolyte**
https://darkestdungeon.wiki.gg/wiki/Cultist_Acolyte

**CultistCutthroat**
https://darkestdungeon.wiki.gg/wiki/Brigand_Cutthroat

**Comment by superesl555** [comment]
Забираю
