### ISSUE TITLE
Реализовать Item

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#53]
дочерний от RangedSkill. 

- Конструктор такой же как у родителя и делегирует ему все параметры.

- имеет функцию std::vector<std::vector<char> > draw()

- Дочерние классы реализовать подобию enemies/имя персонажа/Название скила, но наследовать от item. Сами дочерние сохраняем: заголовки в include/items/, исходники в src/items/. 

https://darkestdungeon.wiki.gg/wiki/Trinkets - отсюда любые три НЕ ПОХОЖИХ. Это просто пассивные эффекты. Поэтому 
https://darkestdungeon.wiki.gg/wiki/Houndmaster -отсюда навык Lick Wounds. Рисунок - колба с зельем

**Comment by Abdkait** [comment]
дай схаваю её
