### ISSUE TITLE
Реализовать героев

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#59]
Реализовывать по подобию врагов. 

- Примеры реализации скилов и врагов в подпапках include/enemies и src/enemies. 
- Пример как обрабатывать эффект Mark(на вики увидите) в src/Webber/Web.cpp. 
- Героев наследовать от entity::Hero. заголовки скилов и класса самого персонажа помещать в include/heroes/Имя героя/. Исходники скиллов и класса самого персонажа помещать в src/heroes/Имя героя/. 

- Основное отличие героя от врага - у героя есть свой урон. Поэтому для генерации урона вместо generators::EffectGenerator::generateImmediateCharacteristicEffect\<effects::Damage\>(crited, минимальное чилсо, максимальное число) использовать generators::EffectGenerator::generateHeroDamage\<effects::Damage\>(crited, actor, модификатор в процентах(целое число)). 

- Если нужно изменить характеристику персонажа на какой-то процент, то для получения текущего значения характеристики использовать entity->getReal(), потому что entity->get() возвращает характеристику с учетом примененных эффектов. 
- На вики "PROT" означает защиту. У нас это Characteristics::defence. 
- KnockBack - ForceMove(1), Forward - Move(-1)
- Слова Stealth, Stress, непонятные значки игнорируем.

Герои:
https://darkestdungeon.wiki.gg/wiki/Bounty_Hunter
https://darkestdungeon.wiki.gg/wiki/Hellion
https://darkestdungeon.wiki.gg/wiki/Man-at-Arms
https://darkestdungeon.wiki.gg/wiki/Musketeer

**Comment by Lledely** [comment]
mine

**Comment by Lledely** [comment]
not mine

**Comment by BaGGeRTeaMYT** [comment]
smth
