### ISSUE TITLE
Реализовать EnemyEncounter and derived class(discuss about it later

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#6]
**Класс EnemyEncounter:**
Коридор с боем. Дочерний от класса Event,SquadChanger и EffectChanger. Должен иметь функции:
1. void turn(Player*, int index) - в соответствии с параграфом «Боевая система» из файла Андрея. Должен вызывать Player.getMonitor().draw()_(см Player #14)_ в нужные моменты. Должен создатвать BattleField(Player->getSquad, Сгенерированный Squad врагов) _(#39)_ Перед каждым ходом у Entity _(#37)_ который вызывает turnEffects(entity). Если у перса после вызова turnEffects(), isTurnable() < 0, то он пропускает ход. Если персонаж наследован от MarkedAsAutoTurn, то вызывает entity->AutoTurn(battlefield). После окончания боя(персонажи одной из сторон мертвы)  вызывает для каждого Entity на BattleField endBattleTurnEffects(entity). Затем вызывает Player.getMap().getCell(Player.getPosition()).freeMoves(Player*, index).
4. Squad getEnemies - возвращает список врагов. _(#39)_
5. Переопределить draw()_(см Event(#4))_
6. Конструктор EnemyEncounter, который либо будет предопределен в дочерних классах, либо создаст рандомно врагов

**Comment by Lledely** [comment]
gimme task (Немцов)

**Comment by TEHEK1** [comment]
Немного изменил. Чекни

**Comment by TEHEK1** [comment]
Ну понеслась. Я перекрыл Issue @Lledely
