### ISSUE TITLE
SkillActionsGenerator

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#64]
**actions::UseSkill**
Дочерний от Action
Имеет конструктор  UseSkill(<std::shared_ptr\<skillDesigns::RangeSkill\>\> skill, std::shared_ptr\<BattleField\> battleField, std::shared_ptr\<entity::Entity\> actor,
                         std::vector\<std::shared_ptr\<entity::Entity\>\> objects)
Переопределяет act(player*): вызывает skill->use(battleField, actor, objects)

**generators::SkillActionsGenerator**
Функции: 
1. std::set\<shared_ptr\<UseSkill\>\> generateAvailableUseSkills(shared_ptr\<RangeSkill\> skill, shared_ptr\<BattleField\> battleField, shared_ptr<actor> actor) - проблегается по всем подотрезкам battleField-\>getEntities длины skill-\>getSize(надо будет создать виртуальную финальнуюRangeSkill::getSize() которая возвращает m_size) и если skill-\>isUsable(battleField, actor, подотрезок), то добавляет в ответ UseSkill(skill, battleField, actor, отрезок). Возвращает получившийся set

**Comment by Abdkait** [comment]
МОËËË
