### ISSUE TITLE
Реализовать Skill и хотя бы 3 derived classes(skills themselves. Must be Heal, Range attack, Close attack))

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#7]
Пригодятся _(#37)_, _(#39)_
Возвраты строк лучше заменить на возврат какой-нибудь обертки(Например можно сделать свою обертку, дочернюю от exception. и от нее унаследовать все непустые строки)
Все заголовки сложить в папку include/skillDesignes/, сами .cpp файлы в папку src/skillDesignes/. Соответственно добавить в CmakeLists соответствующие изменения.
**Класс Skill**
Должен быть с шаблоном.
Дочерний от BattleFieldChanger. _(#39)_
friend со всеми абстрактными классами из этого Issue.
Должен содержать публичные методы:
1. virtual vector\<int\> getAvaibleRank - возвращает список мест, с которых доступно применение скила. 
2. virtual vector\<int\> getAvaibleAllyTarget - возвращает список мест союзников, на которые можно применить навык
3. virtual vector\<int\> getAvaibleEnemyTarget - возвращает список мест врагов, на которыеможно применить навык
4. final use(, std::vector\<std::shared_ptr\<BattleField\>\> battleField, std::weak_ptr\<Entity\> actor, std::vector\<std::weak_ptr\<Entity\>\> objects). должен кидать ошибку с текстом isUsable(все параметры),  если isUasble вернул непустую строку. Иначе если missed() \<= 0, должен  вызвать unsafeUse(crited(), battleField, actor, objects ). 
5. final virtual std::string isUsable() с теми же параметрами, что и у use. Возвращает строку isDesignUsable, если она непустая, иначе isImplementationUsable.
6. string getName() - возвращает название навыка

Должен содержать protected методы:
1. unsafeUse(bool isCrit, std::vector\<std::shared_ptr\<BattleField\>\> battleField, std::weak_ptr\<Entity\> actor , std::vector\<std::weak_ptr\<Entity>> objects) - Само применение скила. вызывает unsafeSelfUse(isCrit, battleField, actor) и для каждого object из object вызывает unsafetargetUse(isCrit, battleField, object). Переопределять при необходимости. Для большинства умений хватает переопределения unsafeSelfUse и unsafeTargetUse
2. unsafeSelfUse(int isCrit, std::vector\<std::shared_ptr\<BattleField\>\> battleField, std::weak_ptr\<Entity\> object) = 0 - накладывает эффекты на применяющего
3. unsafeTargetUse(int isCrit, std::vector\<std::shared_ptr\<BattleField\>\> battleField, std::weak_ptr\<Entity\> actor, std::weak_ptr\<Entity\> object) = 0 - накладывает эффекты на объекты
7. virtual std::string isImplementationUsable с теми же параметрами, что и у use. (во всех дочерних  классах: Должен возвращать пустую строку, если навык можно применить. Иначе возвращает причину невозможности применить навык.)
8. final int missed() - генерирует случайное число от 0 до 100. Возвращает (actor-\>get(accuracyModifier) + 100 - m_accuracy) - число
9. final int dodged(weak_ptr\<Entity\>) - возвращает Entity-\>dodged() _(#37)_
10. final int resisted(weak_ptr\<Entity\>object, size_t effectHash, crited)  если cited<0 возвращает object-\>resisted(effectHash), иначе возвращает object-\>resisted(effectHash)-20.
11. final int crited() - генерирует случайное число от 0 до 100. Возвращает (actor-\>get(criticalDamageChance)+m_criticalDamageChance) - число
14. final void addEffect(weak_ptr\<Entity\>object, shared_ptr\<Effect\> effect, int crited) - если (Debuff или ForceMove) и resisted(object, trick::hash(typeid(effect).name()))) \> 0, ничего не делает, иначе добавляет effect к object
16. Поле m_accuracy
17. Поле m_criticalDamageChance

Должен содержать private метод:
1. virtual std::string isDesignUsable с теми же параметрами, что и у use. 

- Если среди указателей std::weak_ptr\<Entity\> есть те, что не принадлежат battleField, возвращает "Some entity not on battleField", 
- Если индекс actor не принадлежит getAvaibleRank() возвращает "Can't act from this rank"
- Иначе если какой-то object союзник с actor и его индекс не принадлежит getAvaibleAllyTarget() возвращает "Can't act on some ally target"
- Иначе если какой-то object не союзник с actor и его индекс не принадлежит getAvaibleEnemyTarget() - "Can't act on some enemy target"
- Иначе возвращает пустую строку. (переопределятся только в определенных абстрактных классах: Должен возвращать пустую строку, если навык можно применить. Иначе возвращает причину невозможности применить навык. )

**Класс SizedSkill**
Должен быть с численным шаблоном. template\<int Size\>.
Дочерний от Skill
Переопределяет isDesignUsable:
если вызов родительского isDesignUsable вернул непустую строку, возвращает ее. Иначе если objects.size()\>Size возвращает "Too many objects". Иначе если objects.size()\>Size возвращает "Too few objects". Иначе возвращает пустую строку.

**Класс UniqueSizedSkill**
Должен быть с численным шаблоном. template\<int Size\>.
Дочерний от SizedSkill\<Size\>
Переопределяет isDesignUsable:
если вызов родительского isDesignUsable вернул непустую строку, возвращает ее. Иначе если в векторе objects есть одинаковые указатели, возвращает "Objects must be unique". Иначе возвращает пустую строку.

**Класс RangeSkill**
Должен быть с численным шаблоном. template\<int Size\>.
Дочерний от UniqueSizedSkill\<Size\>
Имеет публичные методы:

Переопределяет isDesignUsable:
если вызов родительского isDesignUsable вернул непустую строку, возвращает ее. Иначе если в BattleField _(#39)_ переданные объекты лежат не подряд возвращает "Given objects must be in row on the BattleField. Иначе возвращает пустую строку.

Все заголовки сложить в папку include/Entities/Enemies/Название персонажа/, сами .cpp файлы в папку src/Entities/Enemies/Название персонажа/. Соответственно добавить в CmakeLists соответствующие изменения.
Оборачивать Скилы в namespace enemies::ИмяПерсонажа
Должно получиться 
enemies::ИмяПерсонажа::НазваниеСкила
Смотришь графу Abilities и создаешь классы дочерние от RangedSkill с помощью функций 7-9

**BrigandFusilier::**
https://darkestdungeon.wiki.gg/wiki/Brigand_Fusilier/

**BrigandRaider::**
https://darkestdungeon.wiki.gg/wiki/Brigand_Raider
Аналогично

**CultistAcolyte::**
https://darkestdungeon.wiki.gg/wiki/Cultist_Acolyte

**CultistCutthroat**
https://darkestdungeon.wiki.gg/wiki/Webber

**Comment by J3olchara** [comment]
яяяяяяяяяя мояя урааа

**Comment by Lledely** [comment]
gimme task

**Comment by J3olchara** [comment]
> gimme task

не отдам
