### ISSUE TITLE
Реализовать Effect

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#8]
Класс Effect и дочерние должны быть обернуты в namespace effects
**Класс Effect**
friend с EnemyEncounter
имеет публичные методы:
1. конструктор Effect(std::weak_ptr\<Entity\>, std::map\<size_t, int\> modifier) -  Сохраняет ptr в std::weak_ptr\<Entity\>. _(#37)_
5. int getModifier() - возвращает modfier.

имеет protected методы:
7. virtual void turn() = 0 - действие, которое происходит перед началом хода персонажа. Переопределят дочерние классы.
8. virtual void endBattleTurn() = 0 - действие, которое происходит в конце боя. Переопределят дочерние классы.

 **Класс Disease**
Дочерний от Debuff.
1. Конструктор Buff(std::map\<size_t, int\> modifier). - numberOfTurns использует сам класс, а остальные параметры делегирует родительскому конструктору.в shared_ptr\<Entity\> передает null_ptr.
3. void turn() - ничего не делает
4. virtual void endBattleTurn() - ничего не делает

**Класс PassiveBuff**
Дочерний от Buff
1. Конструктор PassiveBuff(std::weak_ptr\<Entity\>, int numberOfBattles, std::map\<size_t, int\> modifier). - numberOfBattles использует сам класс, а остальные параметры делегирует родительскому конструктору
3. добавляет getRemainingBattles() - оставшиеся разы вызова endBattleTurn().
4. void turn() - ничего не делает
5. virtual void endBattleTurn() - имеет счетчик. Если функция вызвана numberOfBattles раз, то удаляет себя из эффектов игрока. _(#37)_

 **Класс Buff**
Дочерний от Effect.
1. Конструктор Buff(std::weak_ptr\<Entity\>, int numberOfTurns, std::map\<size_t, int\> modifier). - numberOfTurns использует сам класс, а остальные параметры делегирует родительскому конструктору
2. добавляет getRemainingTurns() - оставшиеся разы вызова turn().
3. void turn() - имеет счетчик. Если функция вызвана numberOfTurns раз, то удаляет себя из эффектов игрока. _(#37)_
4. virtual void endBattleTurn() - Удаляет себя из эффектов игрока. _(#37)_

**Класс Guard**
Дочерний от Buff
1. Конструктор Guard(std::weak_ptr\<Entity\>, int numberOfTurns, int defenceModifier) - делегирует родительскому классу std::weak_ptr\<Entity\>, int numberOfTurns, std::map\<size_t, int\> в котором defense = defenceModifier, а остальных характеристик нет

**Класс Stun**
Дочерний от Debuff
1. Конструктор Stun(std::weak_ptr\<Entity\>, int numberOfTurns) - делегирует родительскому классу std::weak_ptr\<Entity\>, int numberOfTurns, std::map\<size_t, int\>, в котором turnable=-1.

**Класс PassiveDebuff**
Дочерний от Debuff. - то же, что и PassiveBuff
1. Конструктор PassiveDebuff(std::weak_ptr\<Entity\>, int numberOfBattles, std::map\<size_t, int\> modifier). - numberOfBattles использует сам класс, а остальные параметры делегирует родительскому конструктору
3. добавляет getRemainingBattles() - оставшиеся разы вызова endBattleTurn().
4. void turn() - ничего не делает
6. virtual void endBattleTurn() - имеет счетчик. Если функция вызвана numberOfBattles раз, то удаляет себя из эффектов игрока. _(#37)_

 **Класс Debuff**
Дочерний от Effect. - то же, что и Buff
1. Конструктор Debuff(std::weak_ptr\<Entity\>, int numberOfTurns, std::map\<size_t, int\> modifier). - numberOfTurns использует сам класс, а остальные параметры делегирует родительскому конструктору
2. добавляет getRemainingTurns() - оставшиеся разы вызова turn().
3. void turn() - имеет счетчик. Если функция вызвана numberOfTurns раз, то удаляет себя из эффектов игрока. _(#37)_
4. virtual void endBattleTurn() - Удаляет себя из эффектов игрока. _(#37)_

**Класс AutoAction**
Дочерний от Effect.
1. Конструктор Debuff(std::weak_ptr\<Entity\>, int numberOfTurns, std::map\<size_t, int\> modifier, std::map\<size_t, int\> turner, int crited, int critModifier = 150). - numberOfTurns использует сам класс, turner использует сам класс, а остальные параметры делегирует родительскому конструктору.
2. добавляет getRemainingTurns() - оставшиеся разы вызова turn().
3. int getTurner() - возвращает turner.
4. void turn() - имеет счетчик. Если функция вызвана numberOfTurns раз, то удаляет себя из эффектов игрока. _(#37)_. Иначе для каждой характеристики из turner  меняет характеристику у Entity на характеристика + характеристика из turner.
7. virtual void endBattleTurn() - Удаляет себя из эффектов игрока. _(#37)_

**Класс Bleed**
Дочерний от AutoAction
1. Конструктор Bleed(std::weak_ptr\<Entity\>, int numberOfTurns, int HPturner, int crited, int critModifier = 150) - делегирует родительскому классу (std::weak_ptr\<Entity\>, _int numberOfTurns = numberOfturns, если cited<0, иначе numberOfturns*150/100_ , _пустой std::map\<size_t, int\>_, _std::map\<size_t, int\> в котором HP = HPturner, а остальных характеристик нет_)

**Класс Blight**
Дочерний от AutoAction
1. Конструктор Blight(std::weak_ptr\<Entity\>, int numberOfTurns, int HPturner, int crited, int critModifier = 150) - делегирует родительскому классу (std::weak_ptr\<Entity\>, _если crited<0 int numberOfTurns = numberOfturns, , иначе numberOfturns*critModifer/100_ , _пустой std::map\<size_t, int\>_ , _std::map\<size_t, int\> в котором HP = HPturner, а остальных характеристик нет_)

**Класс ImmediateEffect**
Дочерний от AutoAction
1. Конструктор: ImmediateEffect(std::weak_ptr\<Entity\>, std::map\<size_t, int\> turner). делегирует родительскому классу (std::weak_ptr\<Entity\>, numberOfTurns=0, пустой std::map\<size_t, int\>, turner).

**Класс Damage**
Дочерний от ImmediateEffect
1. Конструктор Damage(std::weak_ptr\<Entity\>, minDamage, maxDamage,  int crited, int critModifier = 150) - Если minDamage< 0 или minDamage > maxDamage бросает. ошибку. Иначе делегирует родительскому классу (std::weak_ptr\<Entity\>, _ std::map\<size_t, int\> в котором если crited<0 HP = -(случайное число от minDamge до maxDamage включительно), иначе HP= -maxDamage*critModifier/100,остальных характеристик нет_)

**Класс Heal**
Дочерний от ImmediateEffect
1. Конструктор Damage(std::weak_ptr\<Entity\>, minHeal, maxHeal,  int crited, int critModifier = 200) - Если minDamage< 0 или minDamage > maxDamage бросает. ошибку. Иначе делегирует родительскому классу (std::weak_ptr\<Entity\>, _ std::map\<size_t, int\> в котором если crited<0 HP = (случайное число от minHeal до maxHeal включительно), иначе HP= maxHeal*critModifier/100,остальных характеристик нет_)

**Класс PercentHeal**
Дочерний от ImmediateEffect
1. Конструктор Damage(std::weak_ptr\<Entity\>, minPercentHeal, maxPercentHeal,  int crited, int critModifier = 200) - Если minDamage< 0 или minDamage > maxDamage бросает. ошибку. Иначе делегирует родительскому классу (std::weak_ptr\<Entity\>, _ std::map\<size_t, int\> в котором если crited<0 HP = Entity->get(maxHP)*(случайное число от minPercentHeal до maxPercentHeal включительно)/100, иначе HP= Entity->get(maxHP)*maxPercentHeal/100*critModifier/100,остальных характеристик нет_)

**Класс Move**
Дочерний от ImmediateEffect
1. Конструктор: Move(std::weak_ptr\<Entity\>, std::weak_ptr\<BattleField\>, int offset) - делегирует родительскому классу (std::weak_ptr\<Entity\>, numberOfTurns=0, пустой std::map\<size_t, int\>). 
3. turn() - Если Entity не принадлежит BattleField, кидает ошибку, иначе вызывает BattleField->moveRelative(Entity, offset). После чего удаляет себя из списка эффектов Entity

**Класс ForceMove**
То же, что и Move
Дочерний от ImmediateEffect
1. Конструктор: Move(std::weak_ptr\<Entity\>, std::weak_ptr\<BattleField\>, int offset) - делегирует родительскому классу (std::weak_ptr\<Entity\>, numberOfTurns=0, пустой std::map\<size_t, int\>). 
3. turn() - Если Entity не принадлежит BattleField, кидает ошибку, иначе вызывает BattleField->moveRelative(Entity, offset). После чего удаляет себя из списка эффектов Entity

**Comment by supersl555** [comment]
Могу тоже взять

**Comment by ilyinAD** [comment]
бэру

**Comment by NAGIBATOR05** [comment]
моя прелесть
