### ISSUE TITLE
Реализовать NPC

### ISSUE THREAD

**Issue by TEHEK1** [TEHEK1/CppDungeon#9]
Класс MarkedAsAutoTurn
имеет функцию void autoTurn(shared_ptr\<BattleField\>) = 0.

**Класс NPC**
Дочерний от Hero и MarkedAsAutoTurn.
Имеет только один скилл, который постоянно применяет в autoTurn(shared_ptr<BattleField>). так, чтобы skill.isUsable вернул пустую строку _(#7)_, _(#37)_
Как делать см в _(#59)_.

https://darkestdungeon.wiki.gg/wiki/Plague_Doctor Скилл Battlefield Medicine

**класс Enemy**
Дочерний от Entity и MarkedAsAutoTurn
Как делать см в enemies/имя персонажа.
Реализовать autoTurn( должен вызывать случайный эффект из списка скилов так, чтобы skill.isUsable вернул пустую строку _(#7)_, _(#37)_)

**Comment by superesl555** [comment]
Беру
